site_name: Recap
site_url: https://docs.recap.cloud
site_description: A Dead Simple Data Catalog for Engineers
site_author: Chris Riccomini
repo_name: recap-cloud/recap
repo_url: https://github.com/recap-cloud/recap
edit_uri: 'https://github.com/recap-cloud/recap/tree/main/docs'
nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - Guides:
      - Configuration: guides/configuration.md
      - Logging: guides/logging.md
    - Python API:
      - recap.catalog: api/recap.catalog.md
      - recap.integrations: api/recap.integrations.md
      - recap.repl: api/recap.repl.md
      - recap.schema: api/recap.schema.md
      - recap.storage: api/recap.storage.md
    - REST API: rest.md
    - Recap CLI: cli.md
theme:
  features:
      - search.suggest
      - search.highlight
      - search.share
      - content.code.annotate
  name: material
  language: en
  logo: img/recap-logo-square.png
  favicon: img/favicon.ico
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
markdown_extensions:
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      toc_depth: 3
      permalink: true
  - mkdocs-typer
plugins:
  - git-revision-date
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_submodules: true
            show_root_toc_entry: false
            show_root_heading: false
            show_object_full_path: false
            docstring_style: sphinx
          paths: [recap]
  - search:
      lang: en
      prebuild_index: true
extra:
  version:
    provider: mike
watch:
  - recap